name: Application CI
on: [push, pull_request]
jobs:
  test:
    name: Application test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Run test
        run: |
          chmod +x mvnw
          ./mvnw -ntp clean verify